spring.application.name=heck-schools
spring.datasource.url=jdbc:postgresql://localhost:5432/heck_schools
spring.datasource.username=postgres
spring.datasource.password=postgresPW
spring.datasource.driver-class-name=org.postgresql.Driver